// 100+ Categorized Indian Ingredients Data for FridgeChef
export const INGREDIENT_CATEGORIES = [
  { id: 'veggies', name: 'Veg & Herbs', icon: '🥦', color: '#E65100' },
  { id: 'masale', name: 'Masale & Spices', icon: '🌶️', color: '#BF360C' },
  { id: 'staples', name: 'Dairy & Staples', icon: '🍚', color: '#D84315' },
  { id: 'sauces', name: 'Sauces & Oils', icon: '🥫', color: '#E64A19' },
  { id: 'pulses', name: 'Pulses & Nuts', icon: '🥜', color: '#C05621' },
  { id: 'fruits', name: 'Fruits', icon: '🍏', color: '#F57C00' },
];

export const INGREDIENTS = [
  // --- Vegetables & Herbs (25+) ---
  { id: 'aloo', name: 'Aloo (Potato)', category: 'veggies', icon: '🥔' },
  { id: 'pyaaz', name: 'Pyaaz (Onion)', category: 'veggies', icon: '🧅' },
  { id: 'tamatar', name: 'Tamatar (Tomato)', category: 'veggies', icon: '🍅' },
  { id: 'hari-mirch', name: 'Hari Mirch (Green Chili)', category: 'veggies', icon: '🌶️' },
  { id: 'adrak', name: 'Adrak (Ginger)', category: 'veggies', icon: '🫚' },
  { id: 'lehsun', name: 'Lehsun (Garlic)', category: 'veggies', icon: '🧄' },
  { id: 'dhaniya-patta', name: 'Dhaniya Patta (Coriander)', category: 'veggies', icon: '🌿' },
  { id: 'palak', name: 'Palak (Spinach)', category: 'veggies', icon: '🥬' },
  { id: 'shimla-mirch', name: 'Shimla Mirch (Capsicum)', category: 'veggies', icon: '🫑' },
  { id: 'gajar', name: 'Gajar (Carrot)', category: 'veggies', icon: '🥕' },
  { id: 'matar', name: 'Matar (Peas)', category: 'veggies', icon: '🫛' },
  { id: 'gobi', name: 'Phool Gobi (Cauliflower)', category: 'veggies', icon: '🥦' },
  { id: 'patta-gobi', name: 'Patta Gobi (Cabbage)', category: 'veggies', icon: '🥬' },
  { id: 'bhindi', name: 'Bhindi (Okra)', category: 'veggies', icon: '🌱' },
  { id: 'kheera', name: 'Kheera (Cucumber)', category: 'veggies', icon: '🥒' },
  { id: 'baingan', name: 'Baingan (Eggplant)', category: 'veggies', icon: '🍆' },
  { id: 'kadi-patta', name: 'Kadi Patta (Curry Leaves)', category: 'veggies', icon: '🍃' },
  { id: 'nimbu', name: 'Nimbu (Lemon)', category: 'veggies', icon: '🍋' },
  { id: 'pudina', name: 'Pudina (Mint)', category: 'veggies', icon: '🌱' },
  { id: 'mooli', name: 'Mooli (Radish)', category: 'veggies', icon: '🌱' },
  { id: 'chukandar', name: 'Chukandar (Beetroot)', category: 'veggies', icon: '🔴' },
  { id: 'sweet-corn', name: 'Sweet Corn', category: 'veggies', icon: '🌽' },
  { id: 'mushroom', name: 'Mushroom', category: 'veggies', icon: '🍄' },
  { id: 'methi', name: 'Methi Patta (Fenugreek)', category: 'veggies', icon: '🌿' },

  // --- Masale & Spices (25+) ---
  { id: 'haldi', name: 'Haldi (Turmeric)', category: 'masale', icon: '🟡' },
  { id: 'jeera', name: 'Jeera (Cumin Seeds)', category: 'masale', icon: '🟤' },
  { id: 'rai', name: 'Rai / Mustard Seeds', category: 'masale', icon: '⚫' },
  { id: 'lal-mirch', name: 'Lal Mirch Powder', category: 'masale', icon: '🌶️' },
  { id: 'garam-masala', name: 'Garam Masala', category: 'masale', icon: '🤎' },
  { id: 'maggi-masala', name: 'Maggi Masala-e-Magic', category: 'masale', icon: '✨' },
  { id: 'dhaniya-powder', name: 'Dhaniya Powder', category: 'masale', icon: '🌾' },
  { id: 'chaat-masala', name: 'Chaat Masala', category: 'masale', icon: '🧂' },
  { id: 'namak', name: 'Salt (Namak)', category: 'masale', icon: '🧂' },
  { id: 'kali-mirch', name: 'Kali Mirch (Black Pepper)', category: 'masale', icon: '⚫' },
  { id: 'kasuri-methi', name: 'Kasuri Methi', category: 'masale', icon: '🍃' },
  { id: 'amchur', name: 'Amchur (Mango Powder)', category: 'masale', icon: '🥭' },
  { id: 'hing', name: 'Hing (Asafoetida)', category: 'masale', icon: '💨' },
  { id: 'saunf', name: 'Saunf (Fennel)', category: 'masale', icon: '🌾' },
  { id: 'tejpatta', name: 'Tej Patta (Bay Leaf)', category: 'masale', icon: '🍂' },
  { id: 'laung', name: 'Laung (Clove)', category: 'masale', icon: '📌' },
  { id: 'dalchini', name: 'Dalchini (Cinnamon)', category: 'masale', icon: '🪵' },
  { id: 'chhoti-elaichi', name: 'Chhoti Elaichi (Cardamom)', category: 'masale', icon: '🟢' },
  { id: 'pav-bhaji-masala', name: 'Pav Bhaji Masala', category: 'masale', icon: '🥘' },
  { id: 'chole-masala', name: 'Chole Masala', category: 'masale', icon: '🧆' },
  { id: 'biryani-masala', name: 'Biryani Masala', category: 'masale', icon: '🍚' },
  { id: 'peri-peri', name: 'Peri Peri Seasoning', category: 'masale', icon: '🔥' },
  { id: 'oregano', name: 'Oregano / Chili Flakes', category: 'masale', icon: '🍕' },
  { id: 'ajwain', name: 'Ajwain (Carom)', category: 'masale', icon: '🌾' },

  // --- Dairy & Staples (25+) ---
  { id: 'dahi', name: 'Dahi (Curd/Yogurt)', category: 'staples', icon: '🥣' },
  { id: 'paneer', name: 'Paneer (Cottage Cheese)', category: 'staples', icon: '🧀' },
  { id: 'cheese', name: 'Cheese Slices / Processed', category: 'staples', icon: '🧀' },
  { id: 'butter', name: 'Butter (Amul)', category: 'staples', icon: '🧈' },
  { id: 'doodh', name: 'Doodh (Milk)', category: 'staples', icon: '🥛' },
  { id: 'bread', name: 'Bread Slices', category: 'staples', icon: '🍞' },
  { id: 'maggi', name: 'Maggi / Instant Noodles', category: 'staples', icon: '🍜' },
  { id: 'anda', name: 'Anda (Eggs)', category: 'staples', icon: '🥚' },
  { id: 'chawal', name: 'Chawal (Rice)', category: 'staples', icon: '🍚' },
  { id: 'leftover-rice', name: 'Bacha Hua Chawal (Leftover Rice)', category: 'staples', icon: '🍚' },
  { id: 'atta', name: 'Atta (Wheat Flour)', category: 'staples', icon: '🌾' },
  { id: 'maida', name: 'Maida (All Purpose Flour)', category: 'staples', icon: '🍚' },
  { id: 'poha', name: 'Poha (Flattened Rice)', category: 'staples', icon: '🥣' },
  { id: 'suji', name: 'Suji / Rawa (Semolina)', category: 'staples', icon: '🌾' },
  { id: 'vermicelli', name: 'Sevaiya / Vermicelli', category: 'staples', icon: '🍝' },
  { id: 'pasta', name: 'Macaroni / Pasta', category: 'staples', icon: '🍝' },
  { id: 'pav', name: 'Pav / Ladi Pav', category: 'staples', icon: '🥯' },
  { id: 'malai', name: 'Malai / Milk Cream', category: 'staples', icon: '🥛' },
  { id: 'oats', name: 'Rolled Oats', category: 'staples', icon: '🥣' },
  { id: 'papad', name: 'Papad', category: 'staples', icon: '🫓' },
  { id: 'roti-leftover', name: 'Leftover Roti', category: 'staples', icon: '🫓' },
  { id: 'biscuit', name: 'Monaco / Parle-G Biscuits', category: 'staples', icon: '🍪' },

  // --- Sauces, Oils & Condiments (15+) ---
  { id: 'ketchup', name: 'Tomato Ketchup', category: 'sauces', icon: '🥫' },
  { id: 'mayo', name: 'Mayonnaise', category: 'sauces', icon: '🫙' },
  { id: 'schezwan', name: 'Schezwan Sauce / Chutney', category: 'sauces', icon: '🌶️' },
  { id: 'green-chutney', name: 'Green Chutney', category: 'sauces', icon: '🟢' },
  { id: 'soy-sauce', name: 'Soy Sauce', category: 'sauces', icon: '🫙' },
  { id: 'vinegar', name: 'Vinegar', category: 'sauces', icon: '🍾' },
  { id: 'oil', name: 'Cooking Oil', category: 'sauces', icon: '🛢️' },
  { id: 'mustard-oil', name: 'Sarson ka Tel (Mustard Oil)', category: 'sauces', icon: '🟡' },
  { id: 'ghee', name: 'Desi Ghee', category: 'sauces', icon: '🛢️' },
  { id: 'achaar', name: 'Achaar (Pickle)', category: 'sauces', icon: '🫙' },
  { id: 'chili-sauce', name: 'Red / Green Chili Sauce', category: 'sauces', icon: '🌶️' },
  { id: 'peanut-butter', name: 'Peanut Butter', category: 'sauces', icon: '🥜' },
  { id: 'honey', name: 'Honey (Shahad)', category: 'sauces', icon: '🍯' },
  { id: 'jam', name: 'Fruit Jam', category: 'sauces', icon: '🍓' },

  // --- Pulses, Beans & Nuts (12+) ---
  { id: 'moong-dal', name: 'Moong Dal', category: 'pulses', icon: '🟡' },
  { id: 'toor-dal', name: 'Toor Dal (Arhar)', category: 'pulses', icon: '🟡' },
  { id: 'chana-dal', name: 'Chana Dal', category: 'pulses', icon: '🟡' },
  { id: 'besan', name: 'Besan (Gram Flour)', category: 'pulses', icon: '🟡' },
  { id: 'rajma', name: 'Rajma (Kidney Beans)', category: 'pulses', icon: '🫘' },
  { id: 'chana', name: 'Kala Chana / Kabuli Chana', category: 'pulses', icon: '🫘' },
  { id: 'mungfali', name: 'Mungfali (Peanuts)', category: 'pulses', icon: '🥜' },
  { id: 'kaju', name: 'Kaju (Cashew)', category: 'pulses', icon: '🌰' },
  { id: 'badam', name: 'Badam (Almonds)', category: 'pulses', icon: '🌰' },
  { id: 'kishmish', name: 'Kishmish (Raisins)', category: 'pulses', icon: '🍇' },
  { id: 'soya-chunks', name: 'Soya Chunks (Nutrela)', category: 'pulses', icon: '🟤' },
  { id: 'sabudana', name: 'Sabudana', category: 'pulses', icon: '⚪' },

  // --- Fruits (10+) ---
  { id: 'kela', name: 'Kela (Banana)', category: 'fruits', icon: '🍌' },
  { id: 'seb', name: 'Seb (Apple)', category: 'fruits', icon: '🍎' },
  { id: 'aam', name: 'Aam (Mango)', category: 'fruits', icon: '🥭' },
  { id: 'papeeta', name: 'Papeeta (Papaya)', category: 'fruits', icon: '🦤' },
  { id: 'santara', name: 'Santara (Orange)', category: 'fruits', icon: '🍊' },
  { id: 'anar', name: 'Anar (Pomegranate)', category: 'fruits', icon: '🔴' },
  { id: 'amrood', name: 'Amrood (Guava)', category: 'fruits', icon: '🍐' },
  { id: 'tarbooz', name: 'Tarbooz (Watermelon)', category: 'fruits', icon: '🍉' },
  { id: 'angoor', name: 'Angoor (Grapes)', category: 'fruits', icon: '🍇' },
  { id: 'nariyal', name: 'Kacha Nariyal / Coconut', category: 'fruits', icon: '🥥' },
];

export const HOSTEL_MODES = [
  { id: 'any', label: 'Gas / All Equipment', icon: '🔥' },
  { id: 'kettle', label: 'Electric Kettle Only', icon: '🫖' },
  { id: 'microwave', label: 'Microwave Only', icon: '📻' },
  { id: 'induction', label: 'Induction / Single Pan', icon: '🍳' },
  { id: 'nogas', label: 'No Fire / No Cooking (Assembly)', icon: '🥪' },
];
